
#define CMD_SET_BASIC_CONFIG 1
#define CMD_SET_ENCODER_CONFIG 2
#define CMD_SET_MOTOR_CONFIG 3
#define CMD_SET_SERIAL_CONFIG 4
#define CMD_SEND_SERIAL_DATA 5
#define CMD_GET_STATUS 6
#define CMD_SET_ANGLE 7

#define CMD_RESET_EEPROM 10
#define CMD_SET_DEMO 15

#define CMD_NULL 255
